Make POSIX compliant

diff --git a/spdl b/spdl
--- a/spdl
+++ b/spdl
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-if [ -f $HOME/.config/spdl/songs.dir ]; then
+if [ -f "$HOME"/.config/spdl/songs.dir ]; then
     SONGS=$(cat "$HOME/.config/spdl/songs.dir")
 else
     mkdir "$HOME/.config/spdl/"
@@ -12,13 +12,13 @@ search () {
     printf "Searching for '$2', please hold...\n\n"
     SEARCHTERM=$(echo "$2" | sed -e "s/ /%20/g" | sed -e "s/#/%23/g" | sed -e "s/\^/%5E/g")
     RESULT=$(curl -s "https://search.stepmaniaonline.net/packs/$SEARCHTERM" | grep -o -P '(?<=/link/).*(?=.zip)')
-    if [ "$RESULT" == "" ]; then echo "No results found!"; else printf "$RESULT\n\n"; fi
+    if [ "$RESULT" = "" ]; then echo "No results found!"; else printf "$RESULT\n\n"; fi
 }
 
 ddl () {
     PACK=$(echo "$2" | sed -e "s/ /%20/g" | sed -e "s/#/%23/g" | sed -e "s/\^/%5E/g")
     printf "Download starting, this may take a while. You will receive a notification when the download is complete.\n\n"
-    cd "$SONGS"
+    cd "$SONGS" || echo "Cannot find Songs directory! Exiting..." && exit
     curl "https://search.stepmaniaonline.net/static/new/$PACK.zip" -o "$2.zip"
     notify-send "Your download of $2 is complete" &
     unzip -qq "$2.zip" > /dev/null 2>&1
