Add Makefile

diff --git a/spdl b/spdl
--- a/spdl
+++ b/spdl
@@ -3,7 +3,7 @@
 ddl () {
 	#make sure the user has set their Songs folder so we can make a variable
 	if [ -f "$HOME"/.config/spdl/songs.dir ]; then
-	        SONGS=$(cat "$HOME/.config/spdl/songs.dir")
+	        SONGS=$(<"$HOME/.config/spdl/songs.dir")
 	else
 	        mkdir -p "$HOME/.config/spdl/"
 	        touch "$HOME/.config/spdl/songs.dir"
@@ -15,28 +15,19 @@ ddl () {
 	echo "Searching for '$2', please hold..."
 	SEARCHTERM=$(echo "$2" | sed "s/ /%20/g" | sed "s/#/%23/g" | sed "s/\^/%5E/g" | sed "s/\!/%21/g")
 	RESULT=$(curl -s "https://search.stepmaniaonline.net/packs/$SEARCHTERM" | grep -o -P '(?<=/link/).*(?=.zip)')
-	if [ "$RESULT" = "" ]; then echo "No results found!" && exit; fi
+	[ "$RESULT" = "" ] && echo "No results found!" && exit
 	PACK="$(printf "$RESULT" | fzf --layout=reverse --height 40%)"
 	FPACK="$(echo "$PACK" | sed "s/ /%20/g" | sed "s/#/%23/g" | sed "s/\^/%5E/g" | sed "s/\!/%21/g")"
-	if [ -d "$SONGS" ]; then
-		cd "$SONGS"
-	else
-		echo "Cannot access Songs directory. Does it exist?" && exit
-	fi
-	if [ "$FPACK" = "" ]; then
-		echo "No pack selected! Terminating."
-		exit
-	fi
+	[ -d "$SONGS" ] && cd "$SONGS" || $(echo "Cannot access Songs directory. Does it exist?" && exit)
+	[ "$FPACK" = "" ] && echo "No pack selected! Terminating." && exit
 	printf "Download starting, this may take a while. You will receive a notification when the download is complete.\n\n"
 	curl "https://search.stepmaniaonline.net/static/new/$FPACK.zip" -o "$PACK.zip"
 	echo ""
 	unzip -qq -o "$PACK.zip" #automatically overwrites pack if it exists
 	rm "$PACK.zip"
-	if [ -f /usr/bin/notify-send ]; then
-		notify-send "Your download of $PACK is complete" &
-		else echo "Your download of $PACK is complete"
-	fi
+	[ -f /usr/bin/notify-send ] && $(notify-send "Your download of $PACK is complete" &) || echo "Your download of $PACK is complete"
 }
+
 
 spdl_help () {
 	printf 'StepMania Pack Downloader (spdl) by swindlesmccoop\n\nUsage: spdl [-dhs] [pack]\n-d, --download: (D)ownload [pack]\n-h, --help: Print this (h)elp message\n\nWhen supplying the pack name, always put the pack name in double quotes\n' && exit 1
